import "./globals.css";
import ThemeFonts from "@/app/Themes";
import { SnackbarProvider } from "./Context/ContextSnack";
import { OrderProvider } from "./Context/ContextCart";

export const metadata = {
  title: "BurgerBlaze",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png", // مسار الأيقونة
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeFonts>
          <SnackbarProvider>
            <OrderProvider>{children}</OrderProvider>
          </SnackbarProvider>
        </ThemeFonts>
      </body>
    </html>
  );
}
